sudo: required
services:
  - docker

before_install:
  - docker build -t chinrobin/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run chinrobin/react-test npm test -- --coverage

after_success:
  - docker build -t chinrobin/multi-client ./client
  - docker build -t chinrobin/multi-nginx ./nginx
  - docker build -t chinrobin/multi-server ./server
  - docker build -t chinrobin/multi-worker ./worker



# script:
#   - docker run -e CI=true USERNAME/react-test npm test